role_cfg = sc_new("role")
sc_add_index(role_cfg, "hash", "name", "name", "lex")
sc_add_index(role_cfg, "text", "name", "name", "lex")
sc_add_index(role_cfg, "tag", "allowed", "allowed", "lex")
sc_save("role", role_cfg)
